### ISSUE TITLE
fastai_xla_extensions on kaggle errors out

### ISSUE THREAD

**Issue by butchland** [butchland/fastai_xla_extensions#25]
Hi I tried using fastai_xla_extensions, but it errored out. 
Have you used it recently in kaggle?

`!pip install -Uqq fastai --upgrade`
ERROR: kornia 0.3.1 has requirement torch==1.5.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: allennlp 1.0.0 has requirement torch<1.6.0,>=1.5.0, but you'll have torch 1.7.1 which is incompatible.

`!pip install -Uqq cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp36-cp36m-linux_x86_64.whl`
ERROR: torch_xla-1.7-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

how do I resolve these errors?

_Originally posted by @johnyquest7 in https://github.com/butchland/fastai_xla_extensions/discussions/21_

**Comment by andreaslillebo** [comment]
> ERROR: torch_xla-1.7-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

The wheel you're trying to use is for python 3.6. Kaggle's TPU kernels now run on python 3.7.

It should work if you use this wheel instead:
```bash
!pip install -Uqq cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl
```

**Comment by johnyquest7** [comment]
@andreaslillebo 
Thanks for the suggestion.
But when I try it - got the following error

`!pip install -Uqq cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl
!pip install -Uqq git+https://github.com/butchland/fastai_xla_extensions.git
!pip install -Uqq fastcore
#!pip install -Uqq fastai`

initial error

> ERROR: kornia 0.3.1 has requirement torch==1.5.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: allennlp 1.0.0 has requirement torch<1.6.0,>=1.5.0, but you'll have torch 1.7.1 which is incompatible.

When I try to import xla - gets the following error

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1b107ae55627> in <module>
      1 import fastai
----> 2 import fastai_xla_extensions.core

/opt/conda/lib/python3.7/site-packages/fastai_xla_extensions/core.py in <module>
     70 # Right now deciding to patch BaseOptimizer instead of add with a PickableOpt(Optimizer) class like in previous versions
     71 from fastcore.basics import patch_to
---> 72 from fastai.optimizer import _BaseOptimizer
     73 
     74 @patch_to(_BaseOptimizer)

/opt/conda/lib/python3.7/site-packages/fastai/optimizer.py in <module>
      7 
      8 # Cell
----> 9 from .torch_basics import *
     10 
     11 # Cell

/opt/conda/lib/python3.7/site-packages/fastai/torch_basics.py in <module>
      9 from .imports import *
     10 from .torch_imports import *
---> 11 from .torch_core import *
     12 from .layers import *
     13 from .losses import *

/opt/conda/lib/python3.7/site-packages/fastai/torch_core.py in <module>
    282 
    283 # Cell
--> 284 if not hasattr(torch,'as_subclass'): torch.as_subclass = torch.Tensor.as_subclass
    285 
    286 # Cell

AttributeError: type object 'Tensor' has no attribute 'as_subclass'

>

**Comment by andreaslillebo** [comment]
@johnyquest7, I've run into a similar error, but in that case, it was because of a mismatch between the pytorch and fastai versions I had installed.

Instead of running the `pip install` commands separately, try running them in one go like this:
```bash
!pip install -Uqq fastai git+https://github.com/butchland/fastai_xla_extensions.git cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl
```

Then I can just import the libraries like this:
```python
import fastai_xla_extensions.core
from fastai.vision.all import *
```

If that still doesn't work, try removing the `qq` (silence errors) flags from pip install like this:
```bash
!pip install -U fastai git+https://github.com/butchland/fastai_xla_extensions.git cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl
```

---

I believe `kornia` is used for the medical imaging part of fastai and `allennlp` is used for the nlp part of fastai. I haven't run into any problems because of these version mismatch errors when working with `fastai.vision`.

**Comment by johnyquest7** [comment]
Changed the order of pip installs and it worked. 
Now the notebook is running. 
But when I look at the TPU usage - it is showing 0%. I think this is a bug in kaggle because training is faster than on CPU. 
will post a link soon

**Comment by johnyquest7** [comment]
https://www.kaggle.com/johnyquest/tpu-with-fastai

**Comment by johnyquest7** [comment]
@butchland we can close the issue. Thanks

**Comment by butchland** [comment]
Thanks for this!
